name: "Podcast Fenerator"
author: "Devanshi AKbari"
description: "Ganerates a feed for a podcast from a yml file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon : "git-branch"
  color: "red"
inputs:
  email:
    description: The commiters email
    required: true
    default: ${{ github.actor}}@localhost
  name:
    description: the committer's name
    required: true
    default: ${{ github.actor }}